plugins {
    id 'com.android.application'
}
android {
    namespace 'com.ryu.forkliftdiagnostic'
    compileSdk 35
    defaultConfig {
        applicationId "com.ryu.forkliftdiagnostic"
        minSdk 26
        targetSdk 35
        versionCode 36
        versionName "0.18-rc-expert-v8.9.2-quick-ui"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release { minifyEnabled false }
    }
}
dependencies {
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
}
