plugins {
    id 'com.android.application'
}
android {
    namespace 'com.ryu.forkliftdiagnostic'
    compileSdk 35
    defaultConfig {
        applicationId "com.ryu.forkliftdiagnostic"
        minSdk 26
        targetSdk 35
        versionCode 18
        versionName "0.18-rc-auto"
    }
    buildTypes {
        release { minifyEnabled false }
    }
}
dependencies {}
