package com.ryu.forkliftdiagnostic;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class EngineExpertDiagnosticActivity extends Activity{
 private JSONObject data; private LinearLayout body; private final int NAVY=Color.rgb(16,38,58),BLUE=Color.rgb(17,117,214),BG=Color.rgb(242,245,247);
 @Override public void onCreate(Bundle b){super.onCreate(b);try{data=new JSONObject(read("engine_diag_d24_v2.json"));String id=getIntent().getStringExtra("graph_id");if(id!=null&&data.getJSONObject("graphs").has(id))node(id,data.getJSONObject("graphs").getJSONObject(id).getString("start"));else home();}catch(Exception e){fatal(e.toString());}}
 private String read(String n)throws Exception{InputStream is=getAssets().open(n);ByteArrayOutputStream os=new ByteArrayOutputStream();byte[] b=new byte[8192];int r;while((r=is.read(b))>0)os.write(b,0,r);return os.toString(StandardCharsets.UTF_8.name());}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 private TextView tv(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.rgb(25,30,35));v.setPadding(dp(3),dp(5),dp(3),dp(5));if(bold)v.setTypeface(null,Typeface.BOLD);return v;}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(12),dp(14),dp(12));c.setBackground(bg(Color.WHITE,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));c.setLayoutParams(p);return c;}
 private Button btn(String s,boolean pri){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setTextColor(pri?Color.WHITE:Color.rgb(25,30,35));b.setBackground(bg(pri?BLUE:Color.rgb(231,236,240),10));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,dp(3),0,dp(3));b.setLayoutParams(p);return b;}
 private void base(String title){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(8),dp(7),dp(8),dp(7));top.setBackgroundColor(NAVY);Button back=new Button(this);back.setText("‹");back.setTextSize(28);back.setTextColor(Color.WHITE);back.setBackgroundColor(Color.TRANSPARENT);back.setOnClickListener(v->onBackPressed());top.addView(back,new LinearLayout.LayoutParams(dp(48),dp(50)));TextView t=tv(title,18,true);t.setTextColor(Color.WHITE);top.addView(t,new LinearLayout.LayoutParams(0,dp(50),1));Button h=new Button(this);h.setText("⌂");h.setTextSize(24);h.setTextColor(Color.WHITE);h.setBackgroundColor(Color.TRANSPARENT);h.setOnClickListener(v->home());top.addView(h,new LinearLayout.LayoutParams(dp(52),dp(50)));ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(10),dp(10),dp(10),dp(30));sv.addView(body);root.addView(top);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
 private void home()throws Exception{base("D24 엔진 현장진단");LinearLayout info=card();info.addView(tv("D24NAP · OEM 950106-01198 기반",17,true));info.addView(tv("부품을 찍는 앱이 아니라 측정→비교→격리→확정 순으로 진행합니다. OEM 미확인 숫자는 만들지 않습니다.",12,false));body.addView(info);Button map=btn("◎ 센서 위치 / 커넥터·ECU 핀맵",true);map.setOnClickListener(v->startActivity(new android.content.Intent(this,EngineSensorMapActivity.class)));body.addView(map);JSONArray cat=data.getJSONArray("catalog");String grp="";for(int i=0;i<cat.length();i++){JSONObject x=cat.getJSONObject(i);if(!grp.equals(x.optString("group"))){grp=x.optString("group");body.addView(tv(grp,16,true));}Button b=btn(x.optString("title"),false);final String id=x.optString("id");b.setOnClickListener(v->{try{node(id,data.getJSONObject("graphs").getJSONObject(id).getString("start"));}catch(Exception e){fatal(e.toString());}});body.addView(b);}}
 private void node(String gid,String nid)throws Exception{JSONObject g=data.getJSONObject("graphs").getJSONObject(gid),n=g.getJSONObject("nodes").getJSONObject(nid);base(g.optString("title"));Button tp=btn("⊙ 이 증상 측정포인트 / 스코프·게이지 바로보기",true);tp.setOnClickListener(v->{android.content.Intent it=new android.content.Intent(this,TestPointLocatorActivity.class);it.putExtra("graph_id",gid);startActivity(it);});body.addView(tp);Button sm=btn("◎ 이 증상 관련 센서 위치 / 핀맵",true);String focusIds="";JSONArray fids=g.optJSONArray("sensor_ids");if(fids!=null){StringBuilder fb=new StringBuilder();for(int fi=0;fi<fids.length();fi++){if(fi>0)fb.append(",");fb.append(fids.optString(fi));}focusIds=fb.toString();}final String ff=focusIds;sm.setOnClickListener(v->{android.content.Intent it=new android.content.Intent(this,EngineSensorMapActivity.class);it.putExtra("focus_ids",ff);startActivity(it);});body.addView(sm);JSONObject c=data.getJSONObject("circuits").getJSONObject(g.getString("circuit"));diagram(c);LinearLayout h=card();h.addView(tv(n.optString("title"),18,true));if(n.optString("question").length()>0)h.addView(tv(n.optString("question"),16,true));section(h,"현장 확인",n.optJSONArray("field_method"),"① ");section(h,"공구",n.optJSONArray("tools"),"• ");body.addView(h);if("result".equals(n.optString("type"))){result(n);Button pr=btn("분해도 / 부품 위치 참고 (품번은 후순위)",false);pr.setOnClickListener(v->openParts("engine",gid));body.addView(pr);return;}JSONArray a=n.optJSONArray("choices");if(a!=null)for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);Button b=btn(o.optString("label"),i==0);final String nx=o.optString("next");b.setOnClickListener(v->{try{node(gid,nx);}catch(Exception e){fatal(e.toString());}});body.addView(b);}}
 private void diagram(JSONObject c)throws Exception{JSONObject d=c.getJSONObject("simplified_diagram");LinearLayout x=card();x.addView(tv("이 고장에 필요한 계통만 재작성",16,true));x.addView(tv("OEM 원본 전체를 복사하지 않고 지금 찍어야 할 전원·센서·제어·기계경로만 표시",12,false));Bitmap bm=draw(d);ImageView iv=new ImageView(this);iv.setImageBitmap(bm);iv.setAdjustViewBounds(true);iv.setScaleType(ImageView.ScaleType.FIT_CENTER);x.addView(iv,new LinearLayout.LayoutParams(-1,dp(300)));JSONArray mp=d.optJSONArray("measure_points");if(mp!=null){x.addView(tv("바로 찍을 위치",14,true));add(x,mp,"• ");}x.addView(tv("OEM 근거 · "+c.optString("sheet"),12,false));body.addView(x);JSONArray u=c.optJSONArray("unverified");if(u!=null){LinearLayout z=card();z.addView(tv("미확정 · 숫자 추정 금지",14,true));add(z,u,"• ");body.addView(z);}}
 private Bitmap draw(JSONObject d)throws Exception{JSONArray ns=d.getJSONArray("nodes"),es=d.getJSONArray("edges");int n=ns.length(),w=1600,cols=Math.min(4,n),rows=(n+cols-1)/cols,h=180+rows*220;Bitmap b=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);c.drawColor(Color.WHITE);Paint p=new Paint(1);p.setColor(NAVY);p.setTextSize(40);p.setTypeface(Typeface.DEFAULT_BOLD);c.drawText(d.optString("title"),40,55,p);Map<String,RectF> boxes=new HashMap<>();float m=40,gap=22,bw=(w-m*2-gap*(cols-1))/cols,bh=125;for(int i=0;i<n;i++){JSONObject x=ns.getJSONObject(i);int r=i/cols,col=i%cols;float l=m+col*(bw+gap),t=105+r*215;boxes.put(x.getString("id"),new RectF(l,t,l+bw,t+bh));}p.setStrokeWidth(6);p.setColor(Color.GRAY);for(int i=0;i<es.length();i++){JSONObject e=es.getJSONObject(i);RectF a=boxes.get(e.getString("from")),z=boxes.get(e.getString("to"));if(a==null||z==null)continue;float x1=a.right,y1=a.centerY(),x2=z.left,y2=z.centerY();if(z.left<=a.left){x1=a.centerX();y1=a.bottom;x2=z.centerX();y2=z.top;}c.drawLine(x1,y1,x2,y2,p);}for(int i=0;i<n;i++){JSONObject x=ns.getJSONObject(i);RectF r=boxes.get(x.getString("id"));p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(235,242,247));c.drawRoundRect(r,18,18,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);p.setColor(NAVY);c.drawRoundRect(r,18,18,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(25,30,35));p.setTextSize(23);p.setTypeface(Typeface.DEFAULT_BOLD);text(c,p,x.optString("label"),r.centerX(),r.centerY());}return b;}
 private void text(Canvas c,Paint p,String s,float x,float y){String[] a=s.split("\\n");float sy=y-(a.length-1)*15;for(String z:a){c.drawText(z,x-p.measureText(z)/2,sy,p);sy+=30;}}
 private void result(JSONObject n){LinearLayout r=card();r.addView(tv("판정",16,true));r.addView(tv(n.optString("result"),17,true));body.addView(r);resultCard("현장 공구",n.optJSONArray("field_tools"));resultCard("다음 확인/재현",n.optJSONArray("field_test"));resultCard("배제된 원인",n.optJSONArray("rule_out"));resultCard("확정 조건",n.optJSONArray("confirm_if"));if(n.optString("disassembly_gate").length()>0){LinearLayout g=card();g.addView(tv("분해/교환 허용조건",16,true));g.addView(tv(n.optString("disassembly_gate"),14,true));body.addView(g);}if(n.optString("oem_limit_note").length()>0){LinearLayout g=card();g.addView(tv("OEM 기준 제한",14,true));g.addView(tv(n.optString("oem_limit_note"),12,false));body.addView(g);}}
 private void resultCard(String t,JSONArray a){if(a==null||a.length()==0)return;LinearLayout c=card();c.addView(tv(t,15,true));add(c,a,"• ");body.addView(c);} private void section(LinearLayout c,String t,JSONArray a,String p){if(a==null||a.length()==0)return;c.addView(tv(t,14,true));add(c,a,p);} private void add(LinearLayout c,JSONArray a,String p){for(int i=0;i<a.length();i++)c.addView(tv(p+a.optString(i),13,false));}
 private void openParts(String domain,String ref){android.content.Intent it=new android.content.Intent(this,PartsReferenceActivity.class);it.putExtra("domain",domain);it.putExtra("ref_id",ref);startActivity(it);}
 private void fatal(String s){TextView t=new TextView(this);t.setText(s);t.setPadding(30,30,30,30);setContentView(t);}
}
