package com.ryu.forkliftdiagnostic;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import android.content.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class PartsReferenceActivity extends Activity{
 private JSONObject data; private LinearLayout body; private final int NAVY=Color.rgb(16,38,58),BLUE=Color.rgb(17,117,214),BG=Color.rgb(242,245,247),GREEN=Color.rgb(20,125,70),GRAY=Color.rgb(110,118,125);
 private SharedPreferences pref; private String currentModel="", currentCode=""; private int currentSerial=-1; private String domain="",ref="";
 @Override public void onCreate(Bundle b){super.onCreate(b);try{data=new JSONObject(read("parts_reference_v1.json"));pref=getSharedPreferences("parts_vehicle_profile",MODE_PRIVATE);loadProfile();domain=getIntent().getStringExtra("domain");ref=getIntent().getStringExtra("ref_id");if(domain==null)domain="";if(ref==null)ref="";render();}catch(Exception e){fatal("부품 DB 오류: "+e);}}
 private String read(String n)throws Exception{InputStream is=getAssets().open(n);ByteArrayOutputStream os=new ByteArrayOutputStream();byte[] b=new byte[8192];int r;while((r=is.read(b))>0)os.write(b,0,r);is.close();return os.toString(StandardCharsets.UTF_8.name());}
 private void loadProfile(){currentModel=pref.getString("model","");currentCode=pref.getString("code","");currentSerial=pref.getInt("serial",-1);}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
 private TextView tv(String s,int sp,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.rgb(25,30,35));v.setPadding(dp(3),dp(5),dp(3),dp(5));if(bold)v.setTypeface(null,Typeface.BOLD);return v;}
 private TextView colorTv(String s,int sp,boolean bold,int color){TextView v=tv(s,sp,bold);v.setTextColor(color);return v;}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(12),dp(14),dp(12));c.setBackground(bg(Color.WHITE,12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));c.setLayoutParams(p);return c;}
 private Button btn(String s,boolean pri){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(14);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setTextColor(pri?Color.WHITE:Color.rgb(25,30,35));b.setBackground(bg(pri?BLUE:Color.rgb(231,236,240),10));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(52));p.setMargins(0,dp(3),0,dp(3));b.setLayoutParams(p);return b;}
 private void render()throws Exception{
  LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(8),dp(7),dp(8),dp(7));top.setBackgroundColor(NAVY);Button back=new Button(this);back.setText("‹");back.setTextSize(28);back.setTextColor(Color.WHITE);back.setBackgroundColor(Color.TRANSPARENT);back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(dp(48),dp(50)));TextView title=tv("분해도 / 장착 위치 참고",18,true);title.setTextColor(Color.WHITE);top.addView(title,new LinearLayout.LayoutParams(0,dp(50),1));root.addView(top);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(10),dp(10),dp(10),dp(30));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
  JSONObject src=data.getJSONObject("source");LinearLayout intro=card();intro.addView(tv(src.optString("document_id")+" · "+src.optString("title"),15,true));intro.addView(tv("정비 우선순위 · 진단과 위치 확인이 먼저이며 품번은 참고정보입니다.",13,true));intro.addView(tv("실제 주문은 차대번호 기준으로 부품점/EPC에서 최종 확인합니다.",12,false));intro.addView(tv("모델코드: D20=FDA0U / D25=FDA0V / D30=FDA0W / D33=FDA0X",11,false));body.addView(intro);
  JSONObject links=data.getJSONObject("links").optJSONObject(domain);JSONObject link=links==null?null:links.optJSONObject(ref);
  if(link==null){if(ref.length()==0){body.addView(tv("주요 정비 부품군",16,true));JSONObject all=data.getJSONObject("groups");Iterator<String> it=all.keys();while(it.hasNext()){String k=it.next();if("WHOLE_LOCATION".equals(k))continue;addGroup(all.getJSONObject(k));}showWholeLocation();return;}LinearLayout c=card();c.addView(tv("연결된 부품군이 없습니다.",15,true));c.addView(tv("진단 ID · "+ref,12,false));body.addView(c);showWholeLocation();return;}
  LinearLayout q=card();q.addView(tv("진단 ID · "+ref,13,true));q.addView(tv("진단결론보다 품번을 먼저 찍지 않습니다. 현재차량 Serial과 일치하는 후보는 표시하되, 옵션/실차구성 확인 전에는 자동 확정하지 않습니다.",12,false));body.addView(q);
  JSONArray gids=link.optJSONArray("groups");JSONObject groups=data.getJSONObject("groups");if(gids!=null)for(int i=0;i<gids.length();i++){JSONObject g=groups.optJSONObject(gids.optString(i));if(g!=null)addGroup(g);}showWholeLocation();addProfileCard();
 }
 private void addProfileCard(){LinearLayout c=card();c.addView(tv("참고 품번 필터 (선택)",15,true));if(profileReady()){c.addView(colorTv("● "+currentModel+" / "+currentCode+" / Serial "+currentSerial,14,true,GREEN));c.addView(tv("구조화된 Serial 범위가 있는 품번은 아래에서 자동으로 ‘적용/제외’ 표시합니다.",11,false));}else{c.addView(colorTv("⚠ 모델/Serial 미설정",14,true,Color.rgb(180,100,10)));c.addView(tv("변경품이 있는 A/C·브레이크·와이퍼 등은 Serial 없이 단일 품번 확정 금지.",11,false));}Button set=btn("모델 / Serial 참고필터 설정",false);set.setOnClickListener(v->showProfileDialog());c.addView(set);body.addView(c);}
 private boolean profileReady(){return currentCode.length()>0&&currentSerial>=0;}
 private void showProfileDialog(){try{final String[] models={"D20S-7","D25S-7","D30S-7","D33S-7"};final String[] codes={"FDA0U","FDA0V","FDA0W","FDA0X"};LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(8),dp(18),0);Spinner sp=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,models);sp.setAdapter(ad);int sel=0;for(int i=0;i<models.length;i++)if(models[i].equals(currentModel))sel=i;sp.setSelection(sel);box.addView(tv("모델",13,true));box.addView(sp);EditText ed=new EditText(this);ed.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);ed.setHint("예: 843");if(currentSerial>=0)ed.setText(String.valueOf(currentSerial));box.addView(tv("Serial 숫자부",13,true));box.addView(ed);new AlertDialog.Builder(this).setTitle("현재 차량 설정").setView(box).setPositiveButton("저장",(dlg,w)->{String s=ed.getText().toString().trim();if(s.length()==0){Toast.makeText(this,"Serial을 입력하세요.",Toast.LENGTH_SHORT).show();return;}try{int n=Integer.parseInt(s);int i=sp.getSelectedItemPosition();pref.edit().putString("model",models[i]).putString("code",codes[i]).putInt("serial",n).apply();loadProfile();try{render();}catch(Exception e){fatal("화면 갱신 오류: "+e);}}catch(Exception e){Toast.makeText(this,"Serial 숫자를 확인하세요.",Toast.LENGTH_SHORT).show();}}).setNegativeButton("취소",null).show();}catch(Exception e){Toast.makeText(this,"차량 설정을 열 수 없습니다.",Toast.LENGTH_SHORT).show();}}
 private int applicability(JSONObject p){JSONArray a=p.optJSONArray("applications");if(a==null||a.length()==0)return 0;if(!profileReady())return 2;for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;if(currentCode.equals(x.optString("code"))&&currentSerial>=x.optInt("min",0)&&currentSerial<=x.optInt("max",999999))return 1;}return -1;}
 private String appText(JSONObject p){JSONArray a=p.optJSONArray("applications");if(a==null)return p.optString("apply");ArrayList<String> ss=new ArrayList<>();for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x!=null)ss.add(x.optString("code")+" "+x.optInt("min")+"~"+x.optInt("max"));}return android.text.TextUtils.join(" / ",ss);}
 private void addGroup(JSONObject g){
  LinearLayout c=card();c.addView(tv(g.optString("title"),17,true));if(g.optString("option").length()>0)c.addView(tv("Parts Book group · "+g.optString("option"),12,false));JSONArray pages=g.optJSONArray("pages");if(pages!=null)c.addView(tv("PDF p"+pages.toString(),11,false));if(g.optBoolean("serial_required",false)){if(profileReady())c.addView(colorTv("현재차량 Serial 적용필터 사용 중",12,true,GREEN));else c.addView(colorTv("⚠ 모델/Serial 확인 후 품번 확정",12,true,Color.rgb(180,100,10)));}if(g.optString("note").length()>0)c.addView(tv(g.optString("note"),12,false));
  JSONArray ps=g.optJSONArray("parts");if(ps!=null){for(int i=0;i<ps.length();i++){JSONObject p=ps.optJSONObject(i);if(p==null)continue;int ap=applicability(p);String mark=ap==1?"✓ 참고 적용범위 · ":ap==-1?"✕ 참고 범위 외 · ":ap==2?"? Serial 미설정 · ":"• ";int col=ap==1?GREEN:ap==-1?GRAY:Color.rgb(25,30,35);c.addView(colorTv(mark+p.optString("no")+" · "+p.optString("name"),14,true,col));String at=appText(p);if(at.length()>0)c.addView(tv("적용 · "+at,11,false));if(p.optString("note").length()>0)c.addView(tv("주의 · "+p.optString("note"),11,false));}}
  JSONArray views=g.optJSONArray("views");if(views!=null)for(int i=0;i<views.length();i++){final String a=views.optString(i);Button b=btn("분해도 / 위치도 보기 · "+(i+1),false);b.setOnClickListener(v->showAsset(a));c.addView(b);}body.addView(c);
 }
 private void showWholeLocation(){try{JSONObject g=data.getJSONObject("groups").getJSONObject("WHOLE_LOCATION");LinearLayout c=card();c.addView(tv("차량 전체 위치 차트",16,true));c.addView(tv("부품 위치를 찾을 때 전체 차량 기준 방향 확인용",12,false));JSONArray v=g.getJSONArray("views");for(int i=0;i<v.length();i++){final String a=v.optString(i);Button b=btn("Location Chart · "+(i+1),false);b.setOnClickListener(x->showAsset(a));c.addView(b);}body.addView(c);}catch(Exception ignore){}}
 private void showAsset(String a){try{InputStream is=getAssets().open(a);Bitmap bm=BitmapFactory.decodeStream(is);is.close();if(bm==null)return;Dialog d=new Dialog(this);ScrollView sv=new ScrollView(this);ImageView iv=new ImageView(this);iv.setImageBitmap(bm);iv.setAdjustViewBounds(true);iv.setScaleType(ImageView.ScaleType.FIT_CENTER);sv.addView(iv);d.setContentView(sv);d.show();if(d.getWindow()!=null)d.getWindow().setLayout(-1,-1);}catch(Exception e){Toast.makeText(this,"부품도 이미지를 열 수 없습니다.",Toast.LENGTH_SHORT).show();}}
 private void fatal(String s){TextView t=new TextView(this);t.setText(s);t.setPadding(30,30,30,30);setContentView(t);}
}
